### ISSUE TITLE
zip files

### ISSUE THREAD

**Issue by CertifiedRice** [Rusted-Script/Rusted-Script#101]
why are there zip files in the source code? 
why not just make it a regular folder instead of a Zip File?

**Comment by glaukiol1** [comment]
Let me explain. A zip file is the source code compressed to a smaller size, so it doesnt take a long time to downlaod everything. The zip file is 30-40% smaller than the base folder, so it really speeds up download times. The protocol that downloads stuff from the web, FTP, is slow, and a zip or tar.gz file helps speed things up, and one more thing, since GitHub after all is just a Git hosting service, Git sends/receives everything as a zip and tar.gz file. Hope this clears things up!
